export const SHOPIFY_CART_FREE_PRODUCT_APP_METAFIELDS_NAMESPACE = 'cart_free_product';
export const SHOPIFY_CART_FREE_PRODUCT_APP_FIRST_PRODUCT_METAFIELD_KEY = 'first-product-id';
export const SHOPIFY_CART_FREE_PRODUCT_APP_SECOND_PRODUCT_METAFIELD_KEY = 'second-product-id';
export const SHOPIFY_CART_FREE_PRODUCT_APP_FREE_PRODUCT_METAFIELD_KEY = 'free-product-id';
export const SHOPIFY_CART_FREE_PRODUCT_APP_DISCOUNT_CODE_METAFIELD_KEY = 'discount-code';